name: "general_decontamination"
Rscript_binary: "Rscript"
python_binary: "python"

input_dir_base: "data/{sample}/outs/"
input_path_format: "data/{{sample}}/outs/raw_feature_bc_matrix/{data_file}"

# Decontamination parameters
max_contamination: 0.1
delta_first: 10
delta_second: 30

# Clustering parameters
clustering:
  resolution: 0.8
  pca_dims: 20
  min_pca_dim: 1
  max_pca_dim: 20

# QC metrics - general tissue-agnostic
qc_metrics:
  - name: "mt"
    pattern: "^MT-"
    pattern_type: "HGNC"
    description: "Mitochondrial genes"
  - name: "ribo"
    pattern: "^RP[SL]"
    pattern_type: "HGNC"
    description: "Ribosomal genes"
  - name: "PTPRC"
    pattern: "^PTPRC$"
    pattern_type: "HGNC"
    description: "CD45 immune cell marker"

# Marker genes configuration file
marker_genes_config: "config/marker_genes.yaml"

# Tissue type
tissue_type: "general"

samples:
  - samp1
  - samp2
  - samp3
  - samp4